services:
  dev:
    image: forms-clyde
    ports:
      - 5500:5500
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: forms-clyde
    command: sh -c 'while sleep 3600; do :; done'
    volumes:
      - .:/course

